name: PR Test Actions
on: pull_request
jobs:
  Script-A:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"
      - run: yarn check_modules
      - run: yarn install --frozen-lockfile
      - run: yarn run:a
  Script-B:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: "yarn"
      - run: yarn check_modules
      - run: yarn install --frozen-lockfile
      - run: yarn run:a
